# Dataset Settings
dataset: cifar10
num_classes: 10
imb_type: exp        # Exponential imbalance
imb_factor: 0.01785714285     # 100:1 ratio between head and tail classes
data_path: ./data
classifier: 'dot_product_classifier'

# Selection Settings (LAVA)
selection_method: None         # Options: lava, random, None
selection_ratio: 1.0           # Keep 70% of the data based on LAVA scores
device: cuda

# Training Strategy
strategy: DeepSMOTE
loss_type: CE        # Cross Entropy (can be LDAM or CB)
train_rule: None     # Can be 'DRW' to trigger re-weighting mid-training

# Hyperparameters
epochs: 200
start_epoch: 0
print_freq: 10

batch_size: 128
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
lr_steps: [120, 160] # Epochs where the learning rate drops
gamma: 0.1

rand_number: 0
# Augmentation
mixup_alpha: 1.0     # Strength of the mixup interpolation
workers: 4
optimizer: sgd
# Logging & Checkpoints
root_log: ./example/checkpoint_cifar10_deepsmote_0.017
root_model: ./example/checkpoint_cifar10_deepsmote_models
store_name: cifar10_None_deepsmote_exp0.017
cifar_root: ./data
gpu: 1
