# Dataset Settings
dataset: cifar10
num_classes: 10
imb_type: exp        # Exponential imbalance
imb_factor: 0.01     # 100:1 ratio between head and tail classes
data_path: ./data
classifier: 'dot_product_classifier'

# Selection Settings (LAVA)
selection_method: random         # Options: lava, random, none
selection_ratio: 0.7           # Keep 70% of the data based on LAVA scores
device: cuda
augmentation: trivial

# Training Strategy
strategy: ERM
loss_type: CE        # Cross Entropy (can be LDAM or CB)
train_rule: None     # Can be 'DRW' to trigger re-weighting mid-training

# Hyperparameters
epochs: 200
start_epoch: 0
print_freq: 10

batch_size: 128
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
lr_steps: [120, 160] # Epochs where the learning rate drops
gamma: 0.1

rand_number: 0
# Augmentation
mixup_alpha: 1.0     # Strength of the mixup interpolation
workers: 4
optimizer: sgd
# Logging & Checkpoints
root_log: results_random/train
root_model: ./example/checkpoint_cifar10
store_name: cifar10_random_selection_0.7_exp0.01
cifar_root: ./data
gpu: 0

seed: 42