# Dataset Settings
dataset: cifar100
num_classes: 100
imb_type: exp        # Exponential imbalance
imb_factor: 0.01     # 100:1 ratio between head and tail classes
data_path: ./data
classifier: 'dot_product_classifier'

# Selection Settings (LAVA)
method: "none"         # Options: lava, random, none
ratio: 1.0           # Keep 10% of the data based on LAVA scores
device: cuda

# Training Strategy
strategy: Mixup
loss_type: CE        # Cross Entropy (can be LDAM or CB)
train_rule: None     # Can be 'DRW' to trigger re-weighting mid-training

# Hyperparameters
epochs: 200
start_epoch: 0
print_freq: 10

batch_size: 128
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
lr_steps: [120, 160] # Epochs where the learning rate drops
gamma: 0.1

rand_number: 0
# Augmentation
mixup_alpha: 1.0     # Strength of the mixup interpolation
workers: 4
optimizer: sgd
# Logging & Checkpoints
root_log: results/train/cifar100_exp_0.01_Mixup/cifar100_0.01_mixup_only
root_model: example/checkpoint_cifar100_0.01_mixup_only
store_name: cifar100_mixup_exp0.01_only
cifar_root: ./data

